version: '3'

services:
  server:
    build:
      dockerfile: Dockerfile.prod
    ports:
      - '3000:3000'
    networks:
      - hbs-network
    depends_on:
      - db
  db:
    image: mongo:6.0
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGO_DATABASE
    networks:
      - hbs-network
    volumes:
      - hbs-db:/data/db

networks:
  hbs-network:
    driver: bridge

volumes:
  hbs-db:
    driver: local
